var res = {
    im_helloWorld_png : "res/HelloWorld.png",
    im_item_bkg : "res/item_background_game.png",
    im_bg_popup : "res/bg_popup.png",
    im_all_bkg : "res/background_matrix.jpg",
    im_login_bkg : "res/sprite_background_login.png",
    im_cogai_login : "res/sprite_cogai.png",
    im_spritecard_login : "res/sprite_card.png",
    btn_BLUE : "res/btn_blue.png",
    btn_GREEN : "res/btn_green.png",
    btn_YELLOW : "res/btn_yellow.png",
    btn_CYAN : "res/btn_cyan.png",
    btn_dangky : "res/btn_dangky.png",
    btn_dangnhap : "res/btn_dangnhap.png",
    btn_fb : "res/btn_facebook.png",
    btn_choingay : "res/btn_choingay_login.png",
    editBox : "res/edit_login_null.png",
    editBackgruond : "res/edit_password.png",
    btn_back : "res/back.png",
    btn_phone : "res/phone.png",
    background : "res/backgruond.png",
    btn_banbe : "res/banbe.png",
    btn_napxu : "res/NAP-XU.png",
    btn_caidat : "res/CAI-DAT.png",
    btn_xephang : "res/XEP-HANG.png",
    loa : "res/loa.png",
    btn_homthu : "res/homthu.png",
    btn_avatar : "res/khungavataa.png",
    vip : "res/vip1.png",
    chaomung : "res/chaomung.png",
    btn_doithuong : "res/DOI-THUONG.png",
    menu : "res/menu.png",
    xu : "res/xu.png",
    btn_next : "res/next.png",
    btn_next1 : "res/next1.png",
    btn_phom : "res/phom.png",
    btn_sam : "res/sam.png",
    btn_tala : "res/TA-LA.png",
    btn_xocdia : "res/xocdia.png",
    btn_xito : "res/xito.png",
    btn_tlmn : "res/tlmn.png",
    backgroungPopup: "res/backgruondPopup.png",
    img_title_room_play: "res/ic_title_room_play_tlmn.png",
    TABLE_IC_SAO: "res/bk_iconsao.png",
    TABLE_BG_PHONGCHO: "res/bk_phongcho.png",
    TABLE_BG_LST_TABLE: "res/bg_lst_table.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
